# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main_WindowAVOqSx.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Object_Detection(object):
    def setupUi(self, Object_Detection):
        if not Object_Detection.objectName():
            Object_Detection.setObjectName(u"Object_Detection")
        Object_Detection.resize(1193, 696)
        Object_Detection.setStyleSheet(u"background-color: rgb(237, 250, 239);")
        Object_Detection.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QWidget(Object_Detection)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1191, 981))
        self.tabWidget.setStyleSheet(u"")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox_6 = QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 461, 71))
        self.groupBox_6.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.label_18 = QLabel(self.groupBox_6)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 10, 61, 51))
        font = QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.btn_resource_storage = QPushButton(self.groupBox_6)
        self.btn_resource_storage.setObjectName(u"btn_resource_storage")
        self.btn_resource_storage.setGeometry(QRect(230, 10, 100, 51))
        self.btn_resource_storage.setMinimumSize(QSize(100, 0))
        self.btn_resource_storage.setFont(font)
        self.btn_resource_storage.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_stop_2 = QPushButton(self.groupBox_6)
        self.btn_stop_2.setObjectName(u"btn_stop_2")
        self.btn_stop_2.setGeometry(QRect(350, 10, 100, 51))
        self.btn_stop_2.setMinimumSize(QSize(100, 0))
        self.btn_stop_2.setFont(font)
        self.btn_stop_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_start_3 = QPushButton(self.groupBox_6)
        self.btn_start_3.setObjectName(u"btn_start_3")
        self.btn_start_3.setGeometry(QRect(100, 10, 100, 51))
        self.btn_start_3.setMinimumSize(QSize(100, 0))
        self.btn_start_3.setFont(font)
        self.btn_start_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.groupBox_7 = QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 90, 241, 431))
        self.gridLayoutWidget_5 = QWidget(self.groupBox_7)
        self.gridLayoutWidget_5.setObjectName(u"gridLayoutWidget_5")
        self.gridLayoutWidget_5.setGeometry(QRect(20, 20, 211, 251))
        self.gridLayout_6 = QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.ckb_vgg = QCheckBox(self.gridLayoutWidget_5)
        self.ckb_vgg.setObjectName(u"ckb_vgg")

        self.gridLayout_6.addWidget(self.ckb_vgg, 5, 0, 1, 1)

        self.ckb_densenet = QCheckBox(self.gridLayoutWidget_5)
        self.ckb_densenet.setObjectName(u"ckb_densenet")
        self.ckb_densenet.setMinimumSize(QSize(0, 0))
        self.ckb_densenet.setSizeIncrement(QSize(0, 0))

        self.gridLayout_6.addWidget(self.ckb_densenet, 0, 0, 1, 1)

        self.ckb_restnet = QCheckBox(self.gridLayoutWidget_5)
        self.ckb_restnet.setObjectName(u"ckb_restnet")

        self.gridLayout_6.addWidget(self.ckb_restnet, 4, 0, 1, 1)

        self.ckb_efficientnet = QCheckBox(self.gridLayoutWidget_5)
        self.ckb_efficientnet.setObjectName(u"ckb_efficientnet")

        self.gridLayout_6.addWidget(self.ckb_efficientnet, 1, 0, 1, 1)

        self.ckb_inception = QCheckBox(self.gridLayoutWidget_5)
        self.ckb_inception.setObjectName(u"ckb_inception")

        self.gridLayout_6.addWidget(self.ckb_inception, 2, 0, 1, 1)

        self.ckb_xception = QCheckBox(self.gridLayoutWidget_5)
        self.ckb_xception.setObjectName(u"ckb_xception")

        self.gridLayout_6.addWidget(self.ckb_xception, 6, 0, 1, 1)

        self.ckb_mobilenet = QCheckBox(self.gridLayoutWidget_5)
        self.ckb_mobilenet.setObjectName(u"ckb_mobilenet")

        self.gridLayout_6.addWidget(self.ckb_mobilenet, 3, 0, 1, 1)

        self.btn_predict = QPushButton(self.groupBox_7)
        self.btn_predict.setObjectName(u"btn_predict")
        self.btn_predict.setGeometry(QRect(10, 330, 221, 25))
        font1 = QFont()
        font1.setFamily(u"Nirmala UI")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.btn_predict.setFont(font1)
        self.label_22 = QLabel(self.groupBox_7)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 290, 151, 31))
        self.label_22.setFont(font1)
        self.ckb_show_rank = QCheckBox(self.groupBox_7)
        self.ckb_show_rank.setObjectName(u"ckb_show_rank")
        self.ckb_show_rank.setGeometry(QRect(160, 290, 70, 31))
        font2 = QFont()
        font2.setFamily(u"Nirmala UI")
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setWeight(50)
        self.ckb_show_rank.setFont(font2)
        self.ckb_show_rank.setChecked(True)
        self.groupBox_8 = QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(260, 90, 421, 431))
        self.groupBox_8.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.disp_klasifikasi = QLabel(self.groupBox_8)
        self.disp_klasifikasi.setObjectName(u"disp_klasifikasi")
        self.disp_klasifikasi.setGeometry(QRect(10, 20, 400, 400))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_klasifikasi.sizePolicy().hasHeightForWidth())
        self.disp_klasifikasi.setSizePolicy(sizePolicy)
        self.disp_klasifikasi.setMinimumSize(QSize(400, 400))
        self.disp_klasifikasi.setStyleSheet(u"background-color: rgb(200, 247, 247);")
        self.disp_klasifikasi.setFrameShape(QFrame.StyledPanel)
        self.disp_klasifikasi.setFrameShadow(QFrame.Sunken)
        self.disp_klasifikasi.setAlignment(Qt.AlignCenter)
        self.groupBox_9 = QGroupBox(self.tab_4)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(690, 10, 491, 511))
        self.gridLayoutWidget_8 = QWidget(self.groupBox_9)
        self.gridLayoutWidget_8.setObjectName(u"gridLayoutWidget_8")
        self.gridLayoutWidget_8.setGeometry(QRect(10, 340, 471, 161))
        self.gridLayout_9 = QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.result_rank_6 = QLabel(self.gridLayoutWidget_8)
        self.result_rank_6.setObjectName(u"result_rank_6")
        self.result_rank_6.setFrameShape(QFrame.Box)
        self.result_rank_6.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.result_rank_6, 1, 5, 1, 1)

        self.result_rank_1 = QLabel(self.gridLayoutWidget_8)
        self.result_rank_1.setObjectName(u"result_rank_1")
        self.result_rank_1.setFrameShape(QFrame.Box)
        self.result_rank_1.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.result_rank_1, 1, 0, 1, 1)

        self.rank_4 = QLabel(self.gridLayoutWidget_8)
        self.rank_4.setObjectName(u"rank_4")
        self.rank_4.setFrameShape(QFrame.Box)
        self.rank_4.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.rank_4, 0, 3, 1, 1)

        self.rank_2 = QLabel(self.gridLayoutWidget_8)
        self.rank_2.setObjectName(u"rank_2")
        self.rank_2.setFrameShape(QFrame.Box)
        self.rank_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.rank_2, 0, 1, 1, 1)

        self.rank_6 = QLabel(self.gridLayoutWidget_8)
        self.rank_6.setObjectName(u"rank_6")
        self.rank_6.setFrameShape(QFrame.Box)
        self.rank_6.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.rank_6, 0, 5, 1, 1)

        self.rank_3 = QLabel(self.gridLayoutWidget_8)
        self.rank_3.setObjectName(u"rank_3")
        self.rank_3.setFrameShape(QFrame.Box)
        self.rank_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.rank_3, 0, 2, 1, 1)

        self.result_rank_5 = QLabel(self.gridLayoutWidget_8)
        self.result_rank_5.setObjectName(u"result_rank_5")
        self.result_rank_5.setFrameShape(QFrame.Box)
        self.result_rank_5.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.result_rank_5, 1, 4, 1, 1)

        self.result_rank_2 = QLabel(self.gridLayoutWidget_8)
        self.result_rank_2.setObjectName(u"result_rank_2")
        self.result_rank_2.setFrameShape(QFrame.Box)
        self.result_rank_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.result_rank_2, 1, 1, 1, 1)

        self.rank_1 = QLabel(self.gridLayoutWidget_8)
        self.rank_1.setObjectName(u"rank_1")
        self.rank_1.setFrameShape(QFrame.Box)
        self.rank_1.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.rank_1, 0, 0, 1, 1)

        self.result_rank_3 = QLabel(self.gridLayoutWidget_8)
        self.result_rank_3.setObjectName(u"result_rank_3")
        self.result_rank_3.setFrameShape(QFrame.Box)
        self.result_rank_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.result_rank_3, 1, 2, 1, 1)

        self.result_rank_4 = QLabel(self.gridLayoutWidget_8)
        self.result_rank_4.setObjectName(u"result_rank_4")
        self.result_rank_4.setFrameShape(QFrame.Box)
        self.result_rank_4.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.result_rank_4, 1, 3, 1, 1)

        self.rank_5 = QLabel(self.gridLayoutWidget_8)
        self.rank_5.setObjectName(u"rank_5")
        self.rank_5.setMinimumSize(QSize(0, 0))
        self.rank_5.setFrameShape(QFrame.Box)
        self.rank_5.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.rank_5, 0, 4, 1, 1)

        self.rank_7 = QLabel(self.gridLayoutWidget_8)
        self.rank_7.setObjectName(u"rank_7")
        self.rank_7.setFrameShape(QFrame.Box)
        self.rank_7.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.rank_7, 0, 6, 1, 1)

        self.result_rank_7 = QLabel(self.gridLayoutWidget_8)
        self.result_rank_7.setObjectName(u"result_rank_7")
        self.result_rank_7.setFrameShape(QFrame.Box)
        self.result_rank_7.setAlignment(Qt.AlignCenter)

        self.gridLayout_9.addWidget(self.result_rank_7, 1, 6, 1, 1)

        self.groupBox_11 = QGroupBox(self.groupBox_9)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 20, 471, 311))
        self.label_34 = QLabel(self.groupBox_11)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 10, 451, 16))
        font3 = QFont()
        font3.setFamily(u"Nirmala UI")
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_34.setFont(font3)
        self.label_34.setAlignment(Qt.AlignCenter)
        self.top_predict = QLabel(self.groupBox_11)
        self.top_predict.setObjectName(u"top_predict")
        self.top_predict.setGeometry(QRect(10, 40, 451, 261))
        self.top_predict.setFont(font1)
        self.top_predict.setFrameShape(QFrame.Box)
        self.top_predict.setAlignment(Qt.AlignCenter)
        self.lcd_clock_3 = QLCDNumber(self.tab_4)
        self.lcd_clock_3.setObjectName(u"lcd_clock_3")
        self.lcd_clock_3.setGeometry(QRect(480, 10, 201, 71))
        self.lcd_clock_3.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.lcd_clock_3.setDigitCount(8)
        self.groupBox_10 = QGroupBox(self.tab_4)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 520, 1171, 131))
        self.groupBox_10.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.textEdit_klasifikasi = QTextEdit(self.groupBox_10)
        self.textEdit_klasifikasi.setObjectName(u"textEdit_klasifikasi")
        self.textEdit_klasifikasi.setGeometry(QRect(10, 20, 1151, 101))
        self.textEdit_klasifikasi.setStyleSheet(u"background-color: rgb(255, 247, 247);\n"
"border-radius:3px;")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox_5 = QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 90, 241, 501))
        self.gridLayoutWidget_3 = QWidget(self.groupBox_5)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(10, 260, 221, 31))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font1)

        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)

        self.ckb_show_predict = QCheckBox(self.gridLayoutWidget_3)
        self.ckb_show_predict.setObjectName(u"ckb_show_predict")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.ckb_show_predict.sizePolicy().hasHeightForWidth())
        self.ckb_show_predict.setSizePolicy(sizePolicy1)
        self.ckb_show_predict.setMinimumSize(QSize(0, 0))
        self.ckb_show_predict.setSizeIncrement(QSize(0, 0))
        self.ckb_show_predict.setBaseSize(QSize(0, 0))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(False)
        font4.setWeight(50)
        self.ckb_show_predict.setFont(font4)
        self.ckb_show_predict.setLayoutDirection(Qt.LeftToRight)
        self.ckb_show_predict.setChecked(True)

        self.gridLayout_3.addWidget(self.ckb_show_predict, 0, 2, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer, 0, 1, 1, 1)

        self.gridLayoutWidget_2 = QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 20, 223, 211))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalSpacer_5 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer_5, 6, 0, 1, 1)

        self.value_green = QLabel(self.gridLayoutWidget_2)
        self.value_green.setObjectName(u"value_green")
        self.value_green.setMinimumSize(QSize(15, 0))
        self.value_green.setFont(font1)
        self.value_green.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.value_green, 3, 2, 1, 1)

        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer_4, 4, 0, 1, 1)

        self.label_4 = QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font1)

        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 2, 0, 1, 1)

        self.slider_green = QSlider(self.gridLayoutWidget_2)
        self.slider_green.setObjectName(u"slider_green")
        self.slider_green.setMaximum(255)
        self.slider_green.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.slider_green, 3, 1, 1, 1)

        self.value_red = QLabel(self.gridLayoutWidget_2)
        self.value_red.setObjectName(u"value_red")
        self.value_red.setMinimumSize(QSize(37, 0))
        self.value_red.setFont(font1)
        self.value_red.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.value_red, 1, 2, 1, 1)

        self.verticalSpacer = QSpacerItem(3, 3, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer, 0, 0, 1, 1)

        self.value_blue = QLabel(self.gridLayoutWidget_2)
        self.value_blue.setObjectName(u"value_blue")
        self.value_blue.setMinimumSize(QSize(15, 0))
        self.value_blue.setFont(font1)
        self.value_blue.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.value_blue, 5, 2, 1, 1)

        self.slider_red = QSlider(self.gridLayoutWidget_2)
        self.slider_red.setObjectName(u"slider_red")
        self.slider_red.setMaximum(255)
        self.slider_red.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.slider_red, 1, 1, 1, 1)

        self.slider_blue = QSlider(self.gridLayoutWidget_2)
        self.slider_blue.setObjectName(u"slider_blue")
        self.slider_blue.setMaximum(255)
        self.slider_blue.setSliderPosition(0)
        self.slider_blue.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.slider_blue, 5, 1, 1, 1)

        self.label_6 = QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font1)

        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)

        self.label_7 = QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font1)

        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)

        self.btn_reset_rgb = QPushButton(self.gridLayoutWidget_2)
        self.btn_reset_rgb.setObjectName(u"btn_reset_rgb")
        self.btn_reset_rgb.setFont(font1)

        self.gridLayout_2.addWidget(self.btn_reset_rgb, 7, 0, 1, 3)

        self.groupBox_3 = QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(260, 80, 661, 511))
        self.groupBox_3.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.disp_main = QLabel(self.groupBox_3)
        self.disp_main.setObjectName(u"disp_main")
        self.disp_main.setGeometry(QRect(10, 20, 640, 480))
        sizePolicy.setHeightForWidth(self.disp_main.sizePolicy().hasHeightForWidth())
        self.disp_main.setSizePolicy(sizePolicy)
        self.disp_main.setMinimumSize(QSize(640, 480))
        self.disp_main.setStyleSheet(u"background-color: rgb(200, 247, 247);")
        self.disp_main.setFrameShape(QFrame.StyledPanel)
        self.disp_main.setFrameShadow(QFrame.Sunken)
        self.disp_main.setAlignment(Qt.AlignCenter)
        self.groupBox_4 = QGroupBox(self.tab_5)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(930, 0, 251, 591))
        self.groupBox_4.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.textEdit = QTextEdit(self.groupBox_4)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 20, 231, 561))
        self.textEdit.setStyleSheet(u"background-color: rgb(246, 247, 247);\n"
"border-radius:3px;")
        self.lcd_clock = QLCDNumber(self.tab_5)
        self.lcd_clock.setObjectName(u"lcd_clock")
        self.lcd_clock.setGeometry(QRect(720, 10, 201, 71))
        self.lcd_clock.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.lcd_clock.setDigitCount(8)
        self.groupBox_2 = QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(450, 10, 261, 71))
        self.groupBox_2.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.gridLayoutWidget = QWidget(self.groupBox_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 10, 241, 51))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.Qlabel_cpu = QLabel(self.gridLayoutWidget)
        self.Qlabel_cpu.setObjectName(u"Qlabel_cpu")
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(True)
        font5.setWeight(75)
        self.Qlabel_cpu.setFont(font5)
        self.Qlabel_cpu.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.Qlabel_cpu, 1, 1, 1, 1)

        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font5)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)

        self.label_2 = QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font5)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.Qlabel_fps = QLabel(self.gridLayoutWidget)
        self.Qlabel_fps.setObjectName(u"Qlabel_fps")
        self.Qlabel_fps.setFont(font5)
        self.Qlabel_fps.setStyleSheet(u"color: rgb(237, 85, 59);")
        self.Qlabel_fps.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.Qlabel_fps, 1, 0, 1, 1)

        self.label_5 = QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font5)
        self.label_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)

        self.Qlabel_ram = QLabel(self.gridLayoutWidget)
        self.Qlabel_ram.setObjectName(u"Qlabel_ram")
        self.Qlabel_ram.setFont(font5)
        self.Qlabel_ram.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.Qlabel_ram, 1, 2, 1, 1)

        self.groupBox = QGroupBox(self.tab_5)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 431, 71))
        self.groupBox.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 51, 51))
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.camlist = QComboBox(self.groupBox)
        self.camlist.setObjectName(u"camlist")
        self.camlist.setGeometry(QRect(70, 10, 133, 51))
        self.camlist.setMinimumSize(QSize(133, 10))
        self.camlist.setMaximumSize(QSize(100, 16777215))
        self.camlist.setFont(font)
        self.camlist.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_start = QPushButton(self.groupBox)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setGeometry(QRect(210, 10, 100, 51))
        self.btn_start.setMinimumSize(QSize(100, 0))
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_stop = QPushButton(self.groupBox)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setGeometry(QRect(320, 10, 100, 51))
        self.btn_stop.setMinimumSize(QSize(100, 0))
        self.btn_stop.setFont(font)
        self.btn_stop.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.frame = QFrame(self.tab_6)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 371, 591))
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(100, 80, 171, 171))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy2)
        self.label_9.setPixmap(QPixmap(u"assets/me.png"))
        self.label_9.setScaledContents(True)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 280, 351, 21))
        font6 = QFont()
        font6.setFamily(u"Nirmala UI")
        font6.setPointSize(16)
        font6.setBold(True)
        font6.setWeight(75)
        self.label_10.setFont(font6)
        self.label_10.setStyleSheet(u"")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 300, 351, 31))
        font7 = QFont()
        font7.setFamily(u"Nirmala UI")
        font7.setPointSize(11)
        font7.setBold(False)
        font7.setWeight(50)
        self.label_11.setFont(font7)
        self.label_11.setStyleSheet(u"")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.frame_2 = QFrame(self.tab_6)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(370, 0, 811, 591))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(50, 100, 431, 31))
        font8 = QFont()
        font8.setFamily(u"Times New Roman")
        font8.setPointSize(17)
        self.label_12.setFont(font8)
        self.label_13 = QLabel(self.frame_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(50, 140, 571, 31))
        self.label_13.setFont(font8)
        self.label_14 = QLabel(self.frame_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(50, 190, 731, 31))
        self.label_14.setFont(font8)
        self.label_15 = QLabel(self.frame_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 220, 741, 31))
        self.label_15.setFont(font8)
        self.label_16 = QLabel(self.frame_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 250, 751, 31))
        self.label_16.setFont(font8)
        self.label_17 = QLabel(self.frame_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(50, 440, 751, 31))
        self.label_17.setFont(font8)
        self.frame_5 = QFrame(self.frame_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(120, 480, 51, 51))
        font9 = QFont()
        font9.setPointSize(7)
        self.frame_5.setFont(font9)
        self.frame_5.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_5.setFrameShape(QFrame.Box)
        self.frame_5.setFrameShadow(QFrame.Sunken)
        self.frame_5.setLineWidth(3)
        self.label_20 = QLabel(self.frame_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 10, 31, 31))
        self.label_20.setPixmap(QPixmap(u"assets/laravel.png"))
        self.label_20.setScaledContents(True)
        self.frame_6 = QFrame(self.frame_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(190, 480, 51, 51))
        self.frame_6.setFont(font9)
        self.frame_6.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_6.setFrameShape(QFrame.Box)
        self.frame_6.setFrameShadow(QFrame.Sunken)
        self.frame_6.setLineWidth(3)
        self.label_21 = QLabel(self.frame_6)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 10, 31, 31))
        self.label_21.setPixmap(QPixmap(u"assets/git.jpg"))
        self.label_21.setScaledContents(True)
        self.frame_9 = QFrame(self.frame_2)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(330, 480, 51, 51))
        self.frame_9.setFont(font9)
        self.frame_9.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_9.setFrameShape(QFrame.Box)
        self.frame_9.setFrameShadow(QFrame.Sunken)
        self.frame_9.setLineWidth(3)
        self.label_24 = QLabel(self.frame_9)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 10, 31, 31))
        self.label_24.setPixmap(QPixmap(u"assets/mongodb.png"))
        self.label_24.setScaledContents(True)
        self.frame_10 = QFrame(self.frame_2)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(400, 480, 51, 51))
        self.frame_10.setFont(font9)
        self.frame_10.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_10.setFrameShape(QFrame.Box)
        self.frame_10.setFrameShadow(QFrame.Sunken)
        self.frame_10.setLineWidth(3)
        self.label_25 = QLabel(self.frame_10)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 10, 31, 31))
        self.label_25.setPixmap(QPixmap(u"assets/sql.png"))
        self.label_25.setScaledContents(True)
        self.frame_11 = QFrame(self.frame_2)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(470, 480, 51, 51))
        self.frame_11.setFont(font9)
        self.frame_11.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_11.setFrameShape(QFrame.Box)
        self.frame_11.setFrameShadow(QFrame.Sunken)
        self.frame_11.setLineWidth(3)
        self.label_27 = QLabel(self.frame_11)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 10, 31, 31))
        self.label_27.setPixmap(QPixmap(u"assets/nodejs.png"))
        self.label_27.setScaledContents(True)
        self.frame_12 = QFrame(self.frame_2)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(540, 480, 51, 51))
        self.frame_12.setFont(font9)
        self.frame_12.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_12.setFrameShape(QFrame.Box)
        self.frame_12.setFrameShadow(QFrame.Sunken)
        self.frame_12.setLineWidth(3)
        self.label_28 = QLabel(self.frame_12)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 10, 31, 31))
        self.label_28.setPixmap(QPixmap(u"assets/terminal.png"))
        self.label_28.setScaledContents(True)
        self.label_29 = QLabel(self.frame_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(50, 320, 741, 31))
        self.label_29.setFont(font8)
        self.frame_4 = QFrame(self.frame_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(50, 480, 51, 51))
        self.frame_4.setFont(font9)
        self.frame_4.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_4.setFrameShape(QFrame.Box)
        self.frame_4.setFrameShadow(QFrame.Sunken)
        self.frame_4.setLineWidth(3)
        self.label_19 = QLabel(self.frame_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 10, 31, 31))
        self.label_19.setPixmap(QPixmap(u"assets/python.png"))
        self.label_19.setScaledContents(True)
        self.frame_8 = QFrame(self.frame_2)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(260, 480, 51, 51))
        self.frame_8.setFont(font9)
        self.frame_8.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_8.setFrameShape(QFrame.Box)
        self.frame_8.setFrameShadow(QFrame.Sunken)
        self.frame_8.setLineWidth(3)
        self.label_23 = QLabel(self.frame_8)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 10, 31, 31))
        self.label_23.setPixmap(QPixmap(u"assets/java.png"))
        self.label_23.setScaledContents(True)
        self.label_30 = QLabel(self.frame_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(50, 350, 741, 31))
        self.label_30.setFont(font8)
        self.label_31 = QLabel(self.frame_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(50, 380, 741, 31))
        self.label_31.setFont(font8)
        self.frame_13 = QFrame(self.frame_2)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(610, 480, 51, 51))
        self.frame_13.setFont(font9)
        self.frame_13.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_13.setFrameShape(QFrame.Box)
        self.frame_13.setFrameShadow(QFrame.Sunken)
        self.frame_13.setLineWidth(3)
        self.label_32 = QLabel(self.frame_13)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 10, 31, 31))
        self.label_32.setPixmap(QPixmap(u"assets/qt.jpg"))
        self.label_32.setScaledContents(True)
        self.frame_14 = QFrame(self.frame_2)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(680, 480, 51, 51))
        self.frame_14.setFont(font9)
        self.frame_14.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(113, 113, 113);")
        self.frame_14.setFrameShape(QFrame.Box)
        self.frame_14.setFrameShadow(QFrame.Sunken)
        self.frame_14.setLineWidth(3)
        self.label_33 = QLabel(self.frame_14)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 10, 31, 31))
        self.label_33.setPixmap(QPixmap(u"assets/cursor.svg"))
        self.label_33.setScaledContents(True)
        self.lcd_clock_2 = QLCDNumber(self.frame_2)
        self.lcd_clock_2.setObjectName(u"lcd_clock_2")
        self.lcd_clock_2.setGeometry(QRect(610, 0, 201, 71))
        self.lcd_clock_2.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.lcd_clock_2.setDigitCount(8)
        self.tabWidget.addTab(self.tab_6, "")
        Object_Detection.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Object_Detection)
        self.statusbar.setObjectName(u"statusbar")
        Object_Detection.setStatusBar(self.statusbar)

        self.retranslateUi(Object_Detection)
        self.slider_red.valueChanged.connect(self.value_red.setNum)
        self.slider_blue.valueChanged.connect(self.value_blue.setNum)
        self.slider_green.valueChanged.connect(self.value_green.setNum)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Object_Detection)
    # setupUi

    def retranslateUi(self, Object_Detection):
        Object_Detection.setWindowTitle(QCoreApplication.translate("Object_Detection", u"Object Detection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Object_Detection", u"Home", None))
        self.groupBox_6.setTitle("")
        self.label_18.setText(QCoreApplication.translate("Object_Detection", u"Resource", None))
        self.btn_resource_storage.setText(QCoreApplication.translate("Object_Detection", u"STORAGE", None))
        self.btn_stop_2.setText(QCoreApplication.translate("Object_Detection", u"CLEAR", None))
        self.btn_start_3.setText(QCoreApplication.translate("Object_Detection", u"CAMERA", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Object_Detection", u"Select Model To Use Predict", None))
        self.ckb_vgg.setText(QCoreApplication.translate("Object_Detection", u"VGG16", None))
        self.ckb_densenet.setText(QCoreApplication.translate("Object_Detection", u"DenseNet121", None))
        self.ckb_restnet.setText(QCoreApplication.translate("Object_Detection", u"ResNet50", None))
        self.ckb_efficientnet.setText(QCoreApplication.translate("Object_Detection", u"EfficientNet", None))
        self.ckb_inception.setText(QCoreApplication.translate("Object_Detection", u"Inception", None))
        self.ckb_xception.setText(QCoreApplication.translate("Object_Detection", u"Xception", None))
        self.ckb_mobilenet.setText(QCoreApplication.translate("Object_Detection", u"MobileNetV2", None))
        self.btn_predict.setText(QCoreApplication.translate("Object_Detection", u"PREDICT", None))
        self.label_22.setText(QCoreApplication.translate("Object_Detection", u"SHOW RANK PREDICT :", None))
        self.ckb_show_rank.setText(QCoreApplication.translate("Object_Detection", u"Active", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("Object_Detection", u"MAIN WINDOW", None))
        self.disp_klasifikasi.setText("")
        self.groupBox_9.setTitle(QCoreApplication.translate("Object_Detection", u"TOP 5 PREDICTED", None))
        self.result_rank_6.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.result_rank_1.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.rank_4.setText(QCoreApplication.translate("Object_Detection", u"RANK 4", None))
        self.rank_2.setText(QCoreApplication.translate("Object_Detection", u"RANK 2", None))
        self.rank_6.setText(QCoreApplication.translate("Object_Detection", u"RANK 6", None))
        self.rank_3.setText(QCoreApplication.translate("Object_Detection", u"RANK 3", None))
        self.result_rank_5.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.result_rank_2.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.rank_1.setText(QCoreApplication.translate("Object_Detection", u"RANK 1", None))
        self.result_rank_3.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.result_rank_4.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.rank_5.setText(QCoreApplication.translate("Object_Detection", u"RANK 5", None))
        self.rank_7.setText(QCoreApplication.translate("Object_Detection", u"RANK 7", None))
        self.result_rank_7.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.groupBox_11.setTitle("")
        self.label_34.setText(QCoreApplication.translate("Object_Detection", u"TOP PREDICT", None))
        self.top_predict.setText(QCoreApplication.translate("Object_Detection", u"result", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("Object_Detection", u"LOG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Object_Detection", u"Klasifikasi Aksara", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Object_Detection", u"Setting", None))
        self.label_8.setText(QCoreApplication.translate("Object_Detection", u"SHOW PREDICTION :", None))
        self.ckb_show_predict.setText(QCoreApplication.translate("Object_Detection", u"Active", None))
        self.value_green.setText(QCoreApplication.translate("Object_Detection", u"0", None))
        self.label_4.setText(QCoreApplication.translate("Object_Detection", u"RED  :", None))
        self.value_red.setText(QCoreApplication.translate("Object_Detection", u"0", None))
        self.value_blue.setText(QCoreApplication.translate("Object_Detection", u"0", None))
        self.label_6.setText(QCoreApplication.translate("Object_Detection", u"GREEN :", None))
        self.label_7.setText(QCoreApplication.translate("Object_Detection", u"BLUE :", None))
        self.btn_reset_rgb.setText(QCoreApplication.translate("Object_Detection", u"RESET", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Object_Detection", u"MAIN WINDOW", None))
        self.disp_main.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("Object_Detection", u"LOG", None))
        self.groupBox_2.setTitle("")
        self.Qlabel_cpu.setText(QCoreApplication.translate("Object_Detection", u"0.0", None))
        self.label_3.setText(QCoreApplication.translate("Object_Detection", u"CPU", None))
        self.label_2.setText(QCoreApplication.translate("Object_Detection", u"FPS", None))
        self.Qlabel_fps.setText(QCoreApplication.translate("Object_Detection", u"0.0", None))
        self.label_5.setText(QCoreApplication.translate("Object_Detection", u"RAM", None))
        self.Qlabel_ram.setText(QCoreApplication.translate("Object_Detection", u"0.0", None))
        self.groupBox.setTitle("")
        self.label.setText(QCoreApplication.translate("Object_Detection", u"Camera", None))
        self.btn_start.setText(QCoreApplication.translate("Object_Detection", u"START", None))
        self.btn_stop.setText(QCoreApplication.translate("Object_Detection", u"STOP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Object_Detection", u"AR Jawa Learn", None))
        self.label_9.setText("")
        self.label_10.setText(QCoreApplication.translate("Object_Detection", u"FX. BIMA YUDHA PRATAMA", None))
        self.label_11.setText(QCoreApplication.translate("Object_Detection", u"Informatika Angkaatan 20", None))
        self.label_12.setText(QCoreApplication.translate("Object_Detection", u"I am a student from Sanata Dharma University", None))
        self.label_13.setText(QCoreApplication.translate("Object_Detection", u"My major is informatics with a focus on intelligent machines", None))
        self.label_14.setText(QCoreApplication.translate("Object_Detection", u"I am versatile and adaptable to various topics (Back-End Web Developer,", None))
        self.label_15.setText(QCoreApplication.translate("Object_Detection", u"Small Front-End Developer \ud83c\udf10, Entry-level designer \ud83c\udfa8, Desktop applications) depending on the project requirements.", None))
        self.label_16.setText(QCoreApplication.translate("Object_Detection", u"I love exploring new tech stacks \ud83d\udcbb and leveraging them to build cool things \ud83d\udee0\ufe0f", None))
        self.label_17.setText(QCoreApplication.translate("Object_Detection", u"\ud83d\udd28 Languages and Tools:", None))
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_24.setText("")
        self.label_25.setText("")
        self.label_27.setText("")
        self.label_28.setText("")
        self.label_29.setText(QCoreApplication.translate("Object_Detection", u"I have tried to deploy the JawaLearn application on the Streamlit website,", None))
        self.label_19.setText("")
        self.label_23.setText("")
        self.label_30.setText(QCoreApplication.translate("Object_Detection", u"but AR cannot be run because there are problems with the package used.", None))
        self.label_31.setText(QCoreApplication.translate("Object_Detection", u"you can see it at \ud83c\udf10 <a href=\"https://jawalearn.streamlit.app\"> JawaLearn.streamlit.app</a>", None))
        self.label_32.setText("")
        self.label_33.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Object_Detection", u"About Me", None))
    # retranslateUi

